### ISSUE TITLE
Nuget Package Won't Install

### ISSUE THREAD

**Issue by kouphax** [NotMyself/Simple.Data.Sqlite#1]
I always get the following error when trying to install this SQLIte package from Nuget - 

"External packages cannot depend on packages that target projects"

There seems to be some nuget issues around this but generally it appears to be associated with the package itself?

http://nuget.codeplex.com/workitem/595

**Comment by NotMyself** [comment]
Yeah, I noticed this this weekend. Seems to be related to the update to NuGet. Haven't had a chance to look into it yet. Will try to get to it this weekend.

**Comment by AlexRussak** [comment]
Is there any update to this? I currently cannot install the SQLite package from NuGet.

**Comment by NotMyself** [comment]
Hi guys sorry this took so long, I have resolved the issue with version 0.6.8.1. Can you confirm that it works for you?

**Comment by NotMyself** [comment]
ok going to close issue.
